### ISSUE TITLE
Source data from?

### ISSUE THREAD

**Issue by sanjmeh** [datameet/PincodeBoundary#2]
Thanks to load these on github and good to keep them pure json. 
It will be great to know the source sites, last updated on and frequency of updates till now, as a useful meta data.
Thanks.

**Comment by devdattaT** [comment]
As given in the readme, the source is the NIC site: http://postoffice.umd.nic.in:8080/nicutility/

I do not know when it was last updated, or the frequency. The scraping date is the same as the Commit date on the Repo

**Comment by sanjmeh** [comment]
Thanks. The site seems to be taken down or is inaccessible. Will try later. Keep up the good work.
